-- CREATE DATABASE todolist


CREATE TABLE users (
  id INT IDENTITY PRIMARY KEY,
  name NVARCHAR(100) NOT NULL,
  email NVARCHAR(150) NOT NULL UNIQUE,
  password NVARCHAR(200) NOT NULL
);

CREATE TABLE tasks (
  id INT IDENTITY PRIMARY KEY,
  userId INT NOT NULL,
  title NVARCHAR(255) NOT NULL,
  description NVARCHAR(MAX) NULL,
  isCompleted BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT FK_Tasks_Users FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);


